FROM alpine:latest
MAINTAINER "hikib <hikib@proton.me>

ENV TZ=Europe/Copenhagen
WORKDIR /web

RUN apk update \
  && apk add --no-cache w3m \
  && wget https://raw.githubusercontent.com/hikib/dot/master/uni.w3m/bookmark.html \
  && wget https://raw.githubusercontent.com/hikib/dot/master/uni.w3m/config

ENTRYPOINT ["w3m", "-B", "-bookmark", "/web/bookmark.html", "-config", "/web/config"]
