---
- name: Check If Docker Exists
  shell: command -v docker
  register: docker_exists
  ignore_errors: yes

- name: Install Dependencies
  when: docker_exists is failed
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add GPG Key
  when: docker_exists is failed
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository To Apt
  when: docker_exists is failed
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  when: docker_exists is failed
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Check If Docker Exists
  shell: command -v docker
  register: docker_exists
  ignore_errors: yes

- name: Install docker-compose
  when: compose_exists is failed
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
