---
- name: Check If Docker Exists
  shell: command -v docker
  register: docker_exists
  ignore_errors: yes

- name: Install Dependencies
  when: docker_exists is failed
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add GPG Key
  when: docker_exists is failed
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository To Apt
  when: docker_exists is failed
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  when: docker_exists is failed
  become: yes
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Check If Docker Is Active
  when: docker_exists is failed
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure Group "docker" exists
  when: docker_exists is failed
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding hiko to Docker Group
  when: docker_exists is failed
  become: yes
  user:
    name: hiko
    groups: docker
    append: yes

- name: Install docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Change file ownership, group, and permissions
  become: yes
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: hiko
    group: hiko
