FROM pandoc/latex:latest

RUN tlmgr update --self && tlmgr install sectsty lastpage ucs fontaxes enumitem pbox ragged2e
RUN tlmgr install sourceserifpro ly1 roboto cooperhewitt

ENTRYPOINT ["pdflatex"]
