FROM alpine:latest
MAINTAINER "hikib <hikib@proton.me>"

# ---- SETUP
ENV TZ=Europe/Copenhagen
RUN apk add --no-cache sudo \
    && adduser -S hikib \
    && echo "hikib ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
User hikib

# ---- APPS
RUN sudo apk update && sudo apk add --no-cache \
    bash \
    bash-completion \
    curl \
    git \
    less \
    less-doc \
    man-pages \
    mandoc-apropos \
    ripgrep \
    shellcheck \
    tmux \
    tree \
    tzdata \
    vim \
    w3m

# ---- COC
RUN sudo apk add --no-cache \
    nodejs \
    yarn \
    npm

# ---- CONFIG
WORKDIR /dotfiles
RUN sudo git clone https://github.com/hikib/scripts \
    && sudo git clone https://github.com/hikib/dot \
    && ./dot/uni.bash/setup.sh \
    && ./dot/uni.vim/setup.sh \
    && ./dot/uni.w3m/setup.sh \
    && ./scripts/setup.sh

RUN ./dot/uni.tmux/setup.sh
RUN sudo apk add --no-cache neovim
RUN ./dot/uni.nvim/setup.sh

# ---- START IN TMUX
WORKDIR /home/hikib

ENTRYPOINT "/bin/bash"
