FROM alpine:latest
MAINTAINER "hikib <hikib@proton.me>"

# ---- SETUP
ENV TZ=Europe/Copenhagen
RUN apk add --no-cache sudo \
    && adduser -S hikib \
    && echo "hikib ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
User hikib

# ---- APPS
RUN sudo apk update && sudo apk add --no-cache \
    bash \
    bash-completion \
    curl \
    git \
    ripgrep \
    shellcheck \
    tmux \
    tree \
    tzdata \
    vim \
    w3m

# ---- CONFIG
WORKDIR /dotfiles
RUN git clone https://github.com/hikib/scripts \
    && git clone https://github.com/hikib/dot \
    && ./dot/uni.bash/setup.sh \
    && ./dot/uni.tmux/setup.sh \
    && ./dot/uni.vim/setup.sh \
    && ./dot/uni.w3m/setup.sh \
    && ./scripts/setup.sh

# ---- START IN TMUX
WORKDIR /home/hikib

ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["tmux", "new", "-s", "dev"]
