FROM ghcr.io/hikib/dev
MAINTAINER "hikib <hikib@proton.me>"

ENV GOPATH="/home/hikib/go"
ENV PATH="$PATH:$GOPATH/bin"

# ---- APPS
RUN sudo apk update \
    && sudo apk add --no-cache go \
    && vim +PlugInstall +qall &>/dev/null \
    && vim +'CocInstall -sync coc-go' +qall &>/dev/null
