FROM docker.io/hikib/dev
MAINTAINER "hikib <hikib@proton.me>"

ENV GOPATH=$HOME/go
ENV PATH="$PATH:$GOPATH/bin"

# ---- APPS
RUN sudo apk update \
    && sudo apk add --no-cache go \
    && vim +PlugInstall +qall &>/dev/null
