#!/usr/bin/env bash

THISDIR=$(dirname $(readlink -f "$0"))
ln -svf "${THISDIR}/vimrc" "${HOME}/.vimrc"

mkdir -p "${HOME}/.vim"
for DOTFILE in after colors ftdetect.vim ftplugin functions.vim mappings.vim spell
do
  ln -svf "${THISDIR}/vim/${DOTFILE}" "${HOME}/.vim/${DOTFILE}"
done

# installing all plugins
curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs \
  "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
vim +PlugInstall +qall &>/dev/null
