#!/usr/bin/env bash

THISDIR=$(dirname $(readlink -f "$0"))
ln -svf "$THISDIR/vimrc" "$HOME/.vimrc"
ln -svf "$THISDIR/vim/after" "$HOME/.vim/after"
ln -svf "$THISDIR/vim/colors" "$HOME/.vim/colors"
ln -svf "$THISDIR/vim/ftdetect.vim" "$HOME/.vim/ftdetect.vim"
ln -svf "$THISDIR/vim/ftplugin" "$HOME/.vim/ftplugin"
ln -svf "$THISDIR/vim/functions.vim" "$HOME/.vim/functions.vim"
ln -svf "$THISDIR/vim/mappings.vim" "$HOME/.vim/mappings.vim"
ln -svf "$THISDIR/vim/spell" "$HOME/.vim/spell"


curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
  "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
vim -T dumb -n -i NONE -es -S <(echo -e "silent! PluginInstall\nqall")
#vim +PlugInstall +qall #2>/dev/null
