---
- name: Getting Scripts Repository
  git:
    repo: "https://{{ my_repo }}/scripts"
    dest: "~/repos/{{ my_repo }}/scripts"
    clone: yes
    update: yes

- name: Linking to ~/.local/bin
  file:
    src: "~/repos/{{ my_repo }}/scripts/bin"
    dest: ~/.local/bin
    state: link
