FROM alpine:latest
MAINTAINER "hikib <hikib@proton.me>

# --- NEED
RUN apk update && apk add --no-cache \
    bash \
    bash-completion \
    curl \
    git \
    shellcheck \
    tmux \
    tree \
    tzdata \
    vim

# --- SETUP
ENV HOME /home
ENV TZ=Europe/Copenhagen

WORKDIR /dotfiles
RUN git clone https://github.com/hikmet-kibar/dot && \
    git clone https://github.com/hikmet-kibar/scripts
RUN ./dot/uni/bash/setup && \
    ./dot/uni/vim/setup && \
    ./dot/uni/tmux/setup && \
    ./scripts/uni/setup

WORKDIR /home

# --- START IN TMUX
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["tmux", "new", "-s", "dev"]

