FROM alpine:latest
MAINTAINER "hikib <hikib@proton.me>

# --- NEED
RUN apk update && apk add --no-cache \
    bash-completion \
    curl \
    git \
    less \
    man-db \
    shellcheck \
    tmux \
    tree \
    tzdata \
    vim \
    wget

WORKDIR /home/repos/github.com/hikmet-kibar
ENV HOME /home

# --- SETUP
RUN git clone https://github.com/hikmet-kibar/dot && \
    git clone https://github.com/hikmet-kibar/scripts && \
    chmod 0756 ./dot/uni/bash/setup \
    ./dot/uni/tmux/setup \
    ./dot/uni/vim/setup \
    ./scripts/uni/setup

# TODO:
# * All scripts in ~/.local/bin need chmod?
#   Different solution?
# * Add a single, minimal setup file?
RUN ./dot/uni/bash/setup && \
    ./dot/uni/vim/setup && \
    ./dot/uni/tmux/setup && \
    ./scripts/uni/setup

ENV TZ=Europe/Copenhagen

WORKDIR /home
CMD ["/bin/bash"]

