---
- hosts: localhost
  gather_facts: true
  vars:
    my_repo: github.com/hikmet-kibar
  roles:
    - role: system
      tags: system_tag
    - role: base
      tags: base_tag
    - role: dev
      tags: dev_tag
    - role: aec
      tags: aec_tag
