---
- name: Update And Packages
  hosts: localhost
  connection: local

  tasks:
  - name: Install System Updates
    become: true
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes

  - name: Install Packages
    become: true
    ansible.builtin.apt:
      package:
      - vim
      - tmux
      - tree
