FROM alpine:latest
MAINTAINER "hikib <hikib@proton.me>

# ---- SETUP
ENV HOME /home
ENV TZ=Europe/Copenhagen

# ---- APPS
RUN apk update && apk add --no-cache \
    bash \
    bash-completion \
    curl \
    git \
    py3-pip \
    python3 \
    shellcheck \
    tmux \
    tree \
    tzdata \
    vim \
    w3m \
    && curl -sSf https://sh.rustup.rs | bash -s -- -y

# ---- CONFIG

WORKDIR /dotfiles
RUN git clone https://github.com/hikib/scripts \
    && git clone https://github.com/hikib/dot \
    && ./dot/uni/bash/setup \
    && ./dot/uni/tmux/setup \
    && ./dot/uni/vim/setup \
    && ./dot/uni/w3m/setup \
    && ./scripts/uni/setup

# ---- START IN TMUX
WORKDIR /home
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["tmux", "new", "-s", "dev"]
