name: Build and push images
on: [push, workflow_dispatch]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and Push dev image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true, false ]

    steps:
      - name: Checkout and Push to Registry action
        uses: actions/checkout@v4

      - name: Install lateset podman
        if: matrix.install_latest
        run: |
          bash .github/install_latest_podman.sh

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build dev
        id: build-dev
        uses: redhat-actions/buildah-build@v2
        with:
          image: dev
          tags: latest
          containerfiles: |
            ./dev/Containerfile

      - name: Push dev
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-dev.outputs.image }}
          tags: ${{ steps.build-dev.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build dev.go
        id: build-dev-go
        uses: redhat-actions/buildah-build@v2
        with:
          image: dev.go
          tags: latest
          containerfiles: |
            ./dev.go/Containerfile

      - name: Push dev.go
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-dev-go.outputs.image }}
          tags: ${{ steps.build-dev-go.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

  build-tool-web:
    name: Build and Push tool.web Images
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build tool.web
        id: build-tool-web
        uses: redhat-actions/buildah-build@v2
        with:
          image: tool.web
          tags: latest
          containerfiles: |
            ./tool.web/Containerfile

      - name: Push tool.web
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-tool-web.outputs.image }}
          tags: ${{ steps.build-tool-web.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
