name: Build and push images
on: [push]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-dev:
    name: Build and Push dev Images
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build dev
        id: build-dev
        uses: redhat-actions/buildah-build@v2
        with:
          image: dev
          tags: latest
          containerfiles: |
            ./dev/Containerfile

      - name: Push dev
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build-dev.outputs.image }}
          tags: ${{ steps.build-dev.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

  build-dev-go:
    name: Build and Push dev.go Images
    needs: build-dev
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build dev.go
        id: build-dev-go
        uses: redhat-actions/buildah-build@v2
        with:
          image: dev.go
          tags: latest
          containerfiles: |
            ./dev.go/Containerfile

      - name: Push dev.go
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build-dev-go.outputs.image }}
          tags: ${{ steps.build-dev-go.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

  build-dev-py:
    name: Build and Push dev.py Images
    needs: build-dev
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build dev.py
        id: build-dev-py
        uses: redhat-actions/buildah-build@v2
        with:
          image: dev.py
          tags: latest
          containerfiles: |
            ./dev.py/Containerfile

      - name: Push dev.py
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build-dev-py.outputs.image }}
          tags: ${{ steps.build-dev-py.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

  build-tool-web:
    name: Build and Push tool.web Images
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build tool.web
        id: build-tool-web
        uses: redhat-actions/buildah-build@v2
        with:
          image: tool.web
          tags: latest
          containerfiles: |
            ./tool.web/Containerfile

      - name: Push tool.web
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build-tool-web.outputs.image }}
          tags: ${{ steps.build-tool-web.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
